plugins {
    id 'java'
}

group = 'com.ironshield.demo'
version = '1.0.0'

repositories {
    mavenCentral()
}

dependencies {
    // Patched: CVE-2020-36518 (jackson-databind stack overflow)
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.13.2.1'

    // Patched: CVE-2022-22965 (Spring4Shell RCE)
    implementation 'org.springframework:spring-web:5.3.18'
}
