plugins {
    id 'java'
}

group = 'com.ironshield.demo'
version = '1.0.0'

repositories {
    mavenCentral()
}

dependencies {
    // Shared Vulnerability
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.12.0'
    
    // Unique Vulnerability to Repo B
    implementation 'org.springframework:spring-web:5.3.15'
}