plugins {
    id 'java'
}

group = 'com.ironshield.demo'
version = '1.0.0'

repositories {
    mavenCentral()
}

dependencies {
    // Patched: CVE-2020-36518 (HIGH) → 2.13.4.2
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.13.4.2'

    // Patched: CVE-2022-22965 Spring4Shell (CRITICAL) → 5.3.18
    implementation 'org.springframework:spring-web:5.3.18'
}